project:
  type: website
  output-dir: docs

website:
  title: "Think Mechanically"
  description: HVAC Information - Tools - and Calculators
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tools"
        href: listTools.qmd

  sidebar:
    title: Navigation
    style: "docked"
    search: true
    contents:
      - text: Home
        href: index.qmd
      - section: "Tools"
        href: listTools.qmd
        contents:
          - text: System Duct Sizing
            href: ductSizingall.qmd
          - text: FilterSizing
            href: filterSizing.qmd
      - section: "About"
        href: about.qmd
        contents:
          - text: About Me
            href: about.qmd
          - text: Resume
            href: resumenoco.qmd
      - section: "WIP"
        href: filterSizingdeprecated.qmd
        contents:
          - text: FilterSizingdep
            href: filterSizingdeprecated.qmd

format:
  html:
    theme:
      light: united
      dark: darkly
    css: styles.css
    toc: true
    echo: false
    brand: _brand.yml
    logo: tmlogo.png
    logo-alt: z-favicon.png




