---
title: Resume
---


## Christopher J. Freeman

### Objective

To present abilities in the field of plumbing and mechanical trades. Including complete commercial and residential design, project management for up to \$2million projects, consulting owners and contractors, Industrial, commercial, and residential service, project management and schedule generation, and estimation.

\
To show that I am highly adaptable in the mechanical trades and have performed in the majority of roles available in contracting companies.

\
In my first job I went from a helper to designing from scratch the entire estimating system after a brief tutelage from the previous estimator who had to retire. Since then I have taught and performed duties for various firms and earned the respect of my peers and customers. I take pride in finding efficient and cost effective methods of performing my job duties while maintaining a high level of workmanship both in the field and working within software.

\
I have been educating, learning, and gathering resources to be able to overcome any situation in the field. If there is an issue where a customer or employer needs a system back online or completed in a timely manner and there are parts that are difficult to procure or personnel untrained on the system I find or determine effective methods of solving those issues and being resourceful. If there are reoccurring issues with field personnel I find effective methods of communicating, training, and motivating the personnel to eliminate those issues. If clients need innovative solutions to complex problems, I excel in providing those solutions and using industry standard references to back-up any claims or suggestions made to ensure there is no doubt that the solutions provided are evidence based and code compliant.\

### Licensure

License \| Number

-   VA Master Tradesman MPLB MHVA MGFC \| 2710058271

-   VA Backflow Prevention Device Worker \| 2717057680

-   DC Plumbing \| PGM1001129\

-   Nate Certification CHP-5 \| 2024 \| Online

### Education

Degree/Certification \| Date Earned \| School\

-   GED \| February 2002 \| Spotsylvania High School

-   Plumbing Apprenticeship \| June 2006 \| Fairfax County Public Schools AC

-   OSHA 10-Hour Training \| March 2003 \| Fairfax County Public Schools ACE

-   HVAC Apprenticeship \| May 2012 \| Fairfax County Public Schools ACE

-   Daikin VRV Certification - Installer \| May 2013 \| Havtech

-   NATE Certification Air to Air Heat PumpService/Installatiohn \| April 2014 \| Johnstone Supply

-   CFC Certification \| March 2014 \| Johnstone Supply

-   Toshiba/Carrier VRF Certification \| May 2014 \| Carrier Enterprise

-   Daikin VRV Certification – Installation and Commissioning \| April 2018 \| Havtech\

## Skills and Abilities

### Key Abilities

-   Problem solving, complex troubleshooting, research, consultation, instruction, and applying technical documentation and streamlining or standardizing processes in the Mechanical Trades\
-   Design, Build, Installation, and Service Plumbing and Mechanical Systems\
-   Code compliance assurance consulting and design assistance\
-   Estimating & value engineering services (while meeting or exceeding specified performance)\
-   Estimation of plumbing, HVAC, refrigeration, and electrical systems\
-   Project Management of plumbing, HVAC, refrigeration, electrical and mechanical systems installation projects\
-   Problem solving and troubleshooting complex issues with mixing valves, circulation systems, VFD’s, chiller and boiler systems, cooling towers, VAV systems, VRF systems, gas and electric tankless water heaters\
-   Complete electrical systems design for smaller facilities (tenant and warehouse spaces)\
-   Technical support to technicians, maintenance personnel, building owners, homeowners, and company staff\
-   Research and investigation of code compliant, industry standard, governmental testing, and novel systems implementations. Exceptional ability to find trustworthy resources for solving problems and avoiding false or misleading information.\
-   Simplifying and standardizing approaches for less experienced personnel by aggregating and consolidating information. Creation of novel documentation for training and field implementation via pdf illustration and calculator creation in Excel and HTML/Javascript\
-   Standardizing estimation processes for labor hours and materials. Determining suitable multipliers for list pricing to automate or easily update materials costs.\
-   Determining the most cost effective materials combinations to achieve desired project outcomes and provide high quality products at a reduced cost in both construction and service
-   Ability to learn new software and systems at a rapid pace. Ability to troubleshoot unfamiliar systems utilizing technical literature and resources. 
-   Design systems to scale utilizing pdf software and CAD resources to minimize necessity for field measurements and layouts when cost effective\

### Job Coordination & Estimation

PDF creation and overlay, submittal documents, O&M manual creation, design coordination with other trades, engineers, architects, and building owners. Development of coordination drawings. Assistance and consulting for commercial facilities owners on self-performing tenant and core building improvement projects

### Plumbing

Sanitary waste and vent, storm piping, gas, chemical drainage, multi horsepower storm and sewage pump controls and installation, gas piping systems, domestic and non potable water systems. Drain cleaning with K50, K60, sewer jetter machine, hot water jetter machine, sewer cameras, and locators. Creation and submittal of original residential and commercial design documents for plan review. Coordination with design engineers on changes for county plan review comment resolutions.

### Fuel Gas Systems

Natural Gas and LP, Design, value engineering, custom regulator selection, main regulator repairs, verification of existing system meter and regulator capacities, overcoming design challenges in areas with very low gas pressures (Bethesda, DC), troubleshooting intermittent gas appliance failures, LP systems selection and design, creation and submittal of original residential and commercial design documents for plan review

### Mechanical and HVAC

VAV systems, rooftop units, design of controls systems for boilers, interlock kitchen equipment, design basic electrical systems, creation and submittal of original residential and commercial design documents for plan review, design grease waste systems, installation, design, and commissioning of VRV/VRF systems, unitary split systems, design, installation and commissioning of mini-split systems, grease duct installation, layout and coordination of mechanical systems, full mechanical projects, cooling tower piping design and installation, VFD installation for HVAC systems, zoning systems, clothes dryer venting, commercial refrigeration controls and piping, fire dampers, steam and hydronic piping, smoke damper commissioning, fire damper commissioning, quality control, walk in cooler fabrication

### Ductwork

Design, verification of SMACNA compliance, redesign, Manual D calculations. Airflow measurements using hot wire anemometers, vane anemometers, pitot tubes and manometers, static pressure probes and manufacturers data. Sketching commercial and residential installations for procurement, fire dampers, fire and smoke dampers, ceiling radiation dampers, balancing, factory fabricated stainless, exhaust systems design and retrofits, fan selection for commercial kitchen exhaust, custom fitting and fire damper fabrication, single and double wall flue design, grease duct layout and fitting, light testing, stainless, aluminum, galvanized, and black iron.

### Insulation

Fiberglass and elastomeric insulation installation, custom cutting and fitting of elastomeric insulation for equipment, pumps, and appurtenances, PVC outdoor coverings for insulation.

### Fire Sprinkler Systems

Repair, partial replacement, backflow preventer testing, underground sprinkler main installation in most local jurisdictions, repair compressed air dry systems, fire panel troubleshooting, electrical interlocking of kitchen hoods for code compliance

### Electrical

Main panel replacements, troubleshooting, verification of code compliance of different wire types, small facilities design (stamped by others), kitchen hood interlocks in restaurant facilities, repairs in breaker panels, disconnects, equipment, transformers, appliances, appurtenances, buck/boost calculations.

### Materials Connections Experience

Solvent welding up to 18”, brazing up to 3”, soldering up to 6”, threading up to 2”, flaring up to 1-1/2”, roll grooving (steel, PVC, and CPVC) up to 6”, tack welding up to 8”, PP fusion systems up to 4”, Propress up to 4”, compression up to 1”, AWWA mechanical joint and flange fittings up to 12”, plastic and CSST fuel gas up to 2, no hub couplings up to 15”, expansion PEX up to 1-1/2”, crimp and compression PEX up to 1”, Ductwork up to 60”

### Heavy Equipment Operation Experience

Mini excavator, skidsteer, aerial boom lift, scissor lift, backhoe, ditch witch, warehouse fork lift, snow plow (large pickup mounted)

### Software Experience

Experienced with Microsoft Office (Excel, MS Word, Outlook, Etc), Planswift, Bluebeam, Wrightsoft Right-Suite Universal, Acrobat DC, Limited experience FastEST, FastDuct, FreeCAD, Sketchup, Microsoft Project. I have created my own estimating templates with Excel using PHCC labor rates for over 15 years, have created detailed estimating templates using Planswift (they limited capability on previous updates) and currently use Bluebeam and Excel. Created my own estimating tools using Bluebeam. Have created exactly to scale tools in Bluebeam on multiple projects to measure and cut piping for prefabrication before installation with very good accuracy.\
Streaming and video recording tools such as OBS and google classroom for teaching purposes. Extensive knowledge of recording software including Reaper, Cubase, Nuendo, and some Pro Tools. Some experience in DaVinci Resolve. Use of Google Meet and Zoom for remote learning. Voicemeeter Potato and ReaRoute to overcome audio routing limitations BMS systems experience in Solidyne, KMC, Siemens, Computrols, iVu, Tracer, limited Honeywell. Mostly service and maintenance related. \### Employment Experience

Job Title \| Company \| Date Range

-   Plumbing Department Manager/Service Technician/Estimator \| Company \| May 2023 – Present\
    ◦ Residential and Commercial plumbing and HVAC service, installation, and management, procurement and estimating of plumbing contracts, and project management on construction projects. BMS controls service for Solidyne and KMC products, Belimo valves and actuators, commercial service for building with Carrier iVu, Trane Tracer, Computrols, and Siemens PCS systems. Commissioning of commercial systems installations and consulting with controls manager on sequences of operation. Service of air cooled and water cooled chillers, boilers, RTU, VAV, water source heat pumps, packaged AC units, and split systems. Directing technicians on particularly difficult service calls and procuring cost effective parts. Inputting service costs in Service Titan dispatch software. Technician training for plumbing and HVAC services.\

-   Project Manager, Estimator \| Company \| November 2021 – May 2023\
    ◦ Residential, Commercial, and Industrial Service and installation of plumbing and HVAC systems, project management for industrial wastewater projects, tenant improvement, office buildings, pool house facilities, and restaurants, house renovations, load calculations, gas calculations, consultations for other mechanical contractors, diagnosing controls systems issues, consulting building owners. 

-   Commercial Service Manager \| Company \| September 2021 – October 2021\
    ◦ Residential, Commercial, and Industrial Service and installation of plumbing and HVAC systems, assist in providing estimates for special projects, creating projects scopes of work, set service pricing, troubleshoot and assist technicians with particularly troublesome systems 

-   Project Manager, Estimator \| Company \| July 2016 – August 2021\
    ◦ Residential Commercial, and Industrial Service and installation of plumbing and HVAC systems, project management for industrial wastewater projects, tenant improvement, office buildings, pool house facilities, and restaurants, house renovations, load calculations, gas calculations, consultations for other mechanical contractors, diagnosing controls systems issues, consulting building owners. 

-   Plumbing Department Manager/Service Technician \| Company \| January 2014 – June 2016\
    ◦ Residential and Commercial plumbing and HVAC service, installation, and management, procurement and estimating of plumbing contracts, and project management assistance on historical facilities, server facilities, military installations, and office buildings. 

-   HVAC IV Instructor \| Fairfax County Public Schools ACE Program\
    ◦ Duties – Create and administer course syllabus on refrigeration cycle and troubleshooting, Manual J Load calculations, Manual D Duct Calculations, Manual S Equipment Selection, Manual T Registers and Grille Placement and selection, airflow calculations, National Electrical Code Fundamentals, International Mechanical Code, International Fuel Gas Code, and journeyman test preparation\

-   Estimator/Project Manager \| Company \| July 2007 – December 2013\
    ◦ Duties: Estimate and manage plumbing and mechanical projects including office buildings, hotels, industrial shipping facilities, wastewater treatment facilities, retail facilities, tenant improvement projects, assist employees on troubleshooting mechanical and plumbing systems, create submittals and project documents, design plumbing projects, coordination drawings, code consulting, QC for government facilities in conjunction with Army Corps of Engineers, military installations, etc.\

-   Plumbing III Instructor \| Fairfax County Public Schools ACE Program \| September 2006 – June 2008\
    ◦ Duties – Create and administer course syllabus for gas piping installation, troubleshooting plumbing systems, blueprint reading, contract documents, and fuel gas code\

-   Foreman \| Company \| June 2006 – July 2007\
    ◦ Duties – Direct crews tradesman on the installation of plumbing systems in hotels and office buildings, track time and expenses, order materials, layout and install plumbing piping systems\

-   Apprentice \| Company \| February 2002 – June 2006\
    ◦ Duties – Installation of plumbing piping systems for hotels, office buildings, residential occupancies, residential and commercial service\

## Some Major Projects Estimated and Managed

-   United States Park Police Stables – Washington, DC (Full Plumbing Design, Estimation, and Project Management)\
-   Food and Beverage Food Production Facility – Complete redesign and installation of plumbing systems, installation of refrigeration systems for large walk-in cooler and adjacent walk-in freezer, consulting and installation of large commercial ovens and dishwashers, gas piping, electrical installation for walk-in coolers, electrical and fuel gas conversion of overseas kitchen equipment including custom orifice fabrication and transformer installation\
-   Poplar Point Pumping Station (plumbing, chemical waste (PP fusion), gray water (reclaimed storm with disinfection), complete insulation installation (fiberglass and armaflex) and mini split systems)\
-   DC Water RAW WWPS 2 (plumbing, hydronics and VRF, stainless steel schedule 40 piping, RPZ installation and testing)\
-   Courtyard Suites Stafford Quantico (full mechanical, RTUs, Duct, VRF, Plumbing, kitchen hoods, grease duct)\
-   MD City treatment plant (plumbing and mini splits)\
-   George Washington’s Mt Vernon Bolton Building Renovations (plumbing and hydronics, chilled water and boiler water piping, VRF installation)\
-   Spencerville Adventist Academy (plumbing)\
-   Ft Belvoir North (Mechanical QC)\
-   UPS Distribution Facility – Newington, VA (plumbing, gas piping)\
-   Metro Center Office Buildings, Alexandria, VA (plumbing)\
-   Aloft Hotel in Loudoun (plumbing, ProVent (Sovent))\
-   Multiple office buildings, hotels, treatment plants in VA, DC, and MD, tenant design build, residential design build, gas piping design\
-   Commercial service for multistory office buildings ranging from basic RTU systems, chiller and boiler systems, VAV systems, and water source heat pump systems\

### Some Noteworthy Service Projects

-   United States Post Office Forensics Laboratory – Chemical Fume Hood calibration and adjustment, VFD repair and replacement, chemical waste repairs, cooling tower repairs\
-   Ft Belvoir – Various Buildings – Repair and replacement of steam piping and boilers, pneumatic controls replacement, repair of centrifugal pump systems, large commercial split systems, backflow preventer testing and repair, Toshiba/Carrier VRF Installation and commissioning\
-   George Washington’s Mt Vernon – Renovations of Plumbing and HVAC systems in O&M building, repairs and drain cleaning in commercial kitchen,\
-   NTIS Data Center – Liebert Server Room unit maintenance and repair, redesign of server room supply and return layout to increases system effectiveness\
-   Idemia – RTU Maintenance consulting and contracting, extensive rehabilitation from previous contractor performing substandard maintenance, additional RTU controls to prevent major failures\
-   5501 Backlick Rd – Complete renovation of public toilet facilities including new variable speed exhaust fans, new waste and domestic water piping, ductwork alterations, sensor water closets and lavatories, installation and layout design of stainless steel toilet partitions and accessories, ductwork redesign for multiple tenant spaces, replacement of water source heat pumps, service and repair of packaged Stultz RTU for server room, repair of mini split systems for auxiliary server room, packaged AC unit repair, cooling tower repair, extensive consulting for building owner group 
-   Brandon Ave. Corporate Center – Design and retrofit of floating point hydronic controls to alleviate tenant complaints due to insufficient granularity of zoning, properly setting VAV setpoints and re-calibration of Computrols VAV controllers. Repairs on cooling tower, package water cooled AC units, boiler, plumbing systems, duct systems.\
